#! /bin/bash -e
#
# Build Docker image

cd $(dirname $0)/..

auto/save-sha-head

echo "--- Building Docker image"

IMAGE_NAME="katdockero/simple-rest-api"
VERSION=$(auto/get-version)

docker build -t ${IMAGE_NAME}:${VERSION} -t ${IMAGE_NAME}:latest .
