#! /bin/bash -e

cd $(dirname $0)/..

auto/save-sha-head

trap "docker-compose down --volumes" 0

docker volume create --name ruby-2.6-bundle-cache > /dev/null
docker-compose run --rm dev sh -c 'bundle check > /dev/null || bundle install --path /usr/local/bundle'
docker-compose run --service-ports --rm dev bundle exec "${@-bash}"
