#! /bin/bash -e
#
# Publish Docker image

cd $(dirname $0)/..

echo "--- Publishing Docker image"

IMAGE_NAME="katdockero/simple-rest-api"
VERSION=$(auto/get-version)

echo "Publishing Docker image: ${IMAGE_NAME}:${VERSION}"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push ${IMAGE_NAME}:${VERSION}
